### ISSUE TITLE
bug: SonarCloud misconfig

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/onroutebc#655]
Two monorepos are being used for three components.  Request another and adjust.

E.g.
```
        include:
          - dir: backend/vehicles
            sonar_projectKey: bcgov_onroutebc_backend
            token: SONAR_TOKEN_BACKEND
          - dir: backend/dops
            sonar_projectKey: bcgov_onroutebc_backend
            token: SONAR_TOKEN_BACKEND         
          - dir: frontend
            sonar_projectKey: bcgov_onroutebc_frontend
            token: SONAR_TOKEN_FRONTEND
```
